### ISSUE TITLE
Crash when opening remote window in 16.21

### ISSUE THREAD

**Issue by trevjonez** [kumpuu/factorio-helicopters#5]
2.12 mod version

```
10665.759 Error CrashHandler.cpp:419: Received SIGSEGV
Factorio crashed. Generating symbolized stacktrace, please wait ...
#0  0x00000001009d46f2 in Logger::logStacktrace(StackTraceInfo*) (in factorio) (Logger.cpp:472)
#1  0x00000001009c344f in CrashHandler::writeStackTrace(CrashHandler::CrashReason) (in factorio) (CrashHandler.cpp:127)
#2  0x00000001009c33d2 in CrashHandler::SignalHandler(int) (in factorio) (CrashHandler.cpp:421)
#3  0x00007fff5c189f5a in 0x00007fff5c189f5a
#4  0x00007fff5c0b0403 in 0x00007fff5c0b0403
#5  0x0000000100d152ca in agui::Widget::applySizeRestrictionsInternal(agui::Style const&) (in factorio) + 42
#6  0x0000000100d1a985 in agui::Widget::applySizeRestrictions(agui::Style const&) (in factorio) + 37
#7  0x00000001001540e8 in StyleSpecification::apply(agui::Style&, agui::Widget*, OptionalFundamentalBase*) const (in factorio) (StyleSpecification.cpp:155)
#8  0x000000010014c42b in CustomGuiElement::buildWidgetRecursively() (in factorio) (CustomGuiElement.cpp:94)
#9  0x000000010014e8a1 in CustomGuiElement::add(CustomGuiElement*) (in factorio) (CustomGuiElement.cpp:334)
#10 0x00000001009095bb in LuaGuiElement::luaAdd(lua_State*) (in factorio) (LuaGuiElement.cpp:360)
#11 0x0000000100c51df7 in LuaBinder<LuaGuiElement>::callWrapper(lua_State*) (in factorio) (LuaBinder.hpp:327)
#12 0x0000000100cbbda8 in luaD_precall(lua_State*, lua_TValue*, int) (in factorio) + 504
#13 0x0000000100cd2c1d in luaV_execute(lua_State*) (in factorio) + 3789
#14 0x0000000100cbc217 in luaD_call(lua_State*, lua_TValue*, int, int) (in factorio) + 103
#15 0x0000000100cbca0d in luaD_pcall(lua_State*, void (*)(lua_State*, void*), void*, long, long) (in factorio) + 93
#16 0x0000000100cb23a8 in lua_pcallk(lua_State*, int, int, int, int, int (*)(lua_State*)) (in factorio) + 216
#17 0x00000001008d2df3 in LuaGameScript::runEventHandler(unsigned int) (in factorio) (LuaGameScript.cpp:746)
#18 0x00000001008cdaf1 in void LuaEventDispatcher::run<InputAction>(unsigned int, unsigned int, bool (LuaGameScript::*)(InputAction const&), InputAction const&) (in factorio) (LuaEventDispatcher.cpp:423)
#19 0x000000010086904d in LuaContext::actionPerformed(InputAction const&) (in factorio) (LuaContext.cpp:164)
#20 0x0000000100695275 in InputHandler::flushActions(bool) (in factorio) (InputHandler.cpp:55)
#21 0x0000000100389814 in GameActionHandler::update() (in factorio) (GameActionHandler.cpp:305)
#22 0x000000010072fd36 in MainLoop::gameUpdateStep(MultiplayerManagerBase*, Scenario*, AppManager*, MainLoop::HeavyMode) (in factorio) (MainLoop.cpp:925)
#23 0x000000010072e311 in MainLoop::gameUpdateLoop(MainLoop::HeavyMode) (in factorio) (MainLoop.cpp:858)
#24 0x00000001009f0744 in WorkerThread::loop() (in factorio) (WorkerThread.cpp:36)
#25 0x0000000100c94f0e in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (WorkerThread::*)(), WorkerThread*> >(void*) (in factorio) (thread:354)
#26 0x00007fff5c1936c1 in 0x00007fff5c1936c1
#27 0x00007fff5c19356d in 0x00007fff5c19356d
#28 0x00007fff5c192c5d in 0x00007fff5c192c5d
10667.991 Error CrashHandler.cpp:128: Map tick at moment of crash: 38739646
10667.991 Error Util.cpp:67: Unexpected error occurred. If you're running the latest version of the game you can help us solve the problem by posting the contents of the log file on the Factorio forums.
Please also include the save file(s), any mods you may be using, and any steps you know of to reproduce the crash.
10706.635 Received SIGTERM, shutting down
```

**Comment by kumpuu** [comment]
Can you test again in 16.22?

**Comment by trevjonez** [comment]
Working well in latest experimental.
